---
- name: Add user to dev group
  hosts: dev
  become: true
  tasks:
    - name: Add User
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - joe
        - sam
