---
- name: Deploy and start Apache HTTPD service
  hosts: webserver
  become: true
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    rule: http

  tasks:
    - name: Required packages are installed and up to date
      ansible.builtin.dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
        state: latest

    - name: The {{ firewall_service }} is started and enabled
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: The {{ web_service }} is started and enabled
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: ensure web content is present
      ansible.builtin.copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: ensure firewall port open for {{ rule }}
      ansible.posix.firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: ensure that web service is configured
  hosts: workstation
  become: false
  tasks:
    - name: Ensure the webserver is reachable
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        status_code: 200  
