---
- name: Install and Configure webservers
  hosts: webservers
  become: true
  tasks:
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: start httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Deploy template to webserver
      ansible.builtin.template:
        src: templates/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
        mode: '0644'
        owner: root
        group: root
      notify: Restart httpd

    - name: Deploy index.html to webserver
      ansible.builtin.copy:
        src: files/
        dest: "/var/www/vhosts/{{ ansible_facts['hostname'] }}/"
        force: true
        mode: '0644'
        owner: root
        group: root

    - name: Configure firewalld to allow webserver
      ansible.posix.firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled  

  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
